# Generated by Django 5.2 on 2025-05-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
