# Generated by Django 5.2 on 2025-05-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="deleted",
            field=models.IntegerField(default=0),
        ),
    ]
