# Generated by Django 5.2 on 2025-05-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_deleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="deleted",
            new_name="is_deleted",
        ),
    ]
