# Generated by Django 5.2 on 2025-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_rename_deleted_payment_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paystack_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
