# Generated by Django 5.2 on 2025-05-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email_verified_at",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
