# Generated by Django 5.2 on 2025-05-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_member_email_verified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
