# Generated by Django 5.2 on 2025-05-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "license_no",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("license_type", models.CharField(max_length=255)),
                ("license_expiry", models.DateField()),
                ("gh_card", models.CharField(max_length=255)),
                ("gh_expiry", models.DateField()),
                ("reg_code", models.CharField(max_length=50)),
                ("fname", models.CharField(max_length=30)),
                ("mname", models.CharField(blank=True, max_length=30, null=True)),
                ("lname", models.CharField(max_length=30)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=2)),
                ("phone", models.CharField(max_length=255)),
                ("whatsapp", models.BigIntegerField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("years_experience", models.IntegerField()),
                ("account_type", models.CharField(max_length=255)),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=255)),
                ("residence", models.CharField(max_length=255)),
                ("medical", models.CharField(max_length=40)),
                ("passport", models.CharField(max_length=255)),
                ("hometown", models.CharField(max_length=255)),
                ("guarantor_no", models.CharField(max_length=255)),
                ("guarantor_name", models.CharField(max_length=255)),
                ("guarantor_residence", models.CharField(max_length=255)),
                (
                    "guarantor_no2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "guarantor_name2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "guarantor_residence2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("emergency_name", models.CharField(max_length=255)),
                ("emergency_no", models.CharField(max_length=255)),
                ("emergency_residence", models.CharField(max_length=30)),
                ("emergency_email", models.EmailField(max_length=254)),
                (
                    "emergency_name2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_no2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_residence2",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "emergency_email2",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("contract_dura", models.CharField(max_length=5)),
                ("is_deleted", models.IntegerField(default=0, max_length=1)),
                ("createuser", models.CharField(blank=True, max_length=30, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modifyuser", models.CharField(blank=True, max_length=30, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
