from django.db import models

# Create your models here.
class Driver(models.Model):
    user = models.ForeignKey('users.Member', on_delete=models.CASCADE, blank=True, null=True)
    license_no = models.CharField(max_length=255, primary_key=True)
    license_type = models.CharField(max_length=255)
    license_expiry = models.DateField()
    gh_card = models.CharField(max_length=255)
    gh_expiry = models.DateField()
    reg_code = models.CharField(max_length=50)
    fname = models.CharField(max_length=30)
    mname = models.CharField(max_length=30, blank=True, null=True)
    lname = models.CharField(max_length=30)
    dob = models.DateField()
    gender = models.CharField(max_length=2)
    phone = models.CharField(max_length=255)
    whatsapp = models.BigIntegerField(null=True, blank=True)
    email = models.EmailField()
    years_experience = models.IntegerField()
    account_type = models.CharField(max_length=255)
    account_name = models.CharField(max_length=255)
    account_number = models.CharField(max_length=255)
    residence = models.CharField(max_length=255)
    medical = models.CharField(max_length=40)
    passport = models.CharField(max_length=255)
    hometown = models.CharField(max_length=255)
    guarantor_no = models.CharField(max_length=255)
    guarantor_name = models.CharField(max_length=255)
    guarantor_residence = models.CharField(max_length=255)
    guarantor_no2 = models.CharField(max_length=255, null=True, blank=True)
    guarantor_name2 = models.CharField(max_length=255, null=True, blank=True)
    guarantor_residence2 = models.CharField(max_length=255, null=True, blank=True)
    emergency_name = models.CharField(max_length=255)
    emergency_no = models.CharField(max_length=255)
    emergency_residence = models.CharField(max_length=30)
    emergency_email = models.EmailField()
    emergency_name2 = models.CharField(max_length=255, null=True, blank=True)
    emergency_no2 = models.CharField(max_length=255, null=True, blank=True)
    emergency_residence2 = models.CharField(max_length=30, null=True, blank=True)
    emergency_email2 = models.EmailField(null=True, blank=True)
    contract_dura = models.CharField(max_length=5)
    is_deleted = models.IntegerField(max_length=1, default=0)
    createuser = models.CharField(max_length=30, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modifyuser = models.CharField(max_length=30, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.fname} {self.lname}"